### ISSUE TITLE
Cannot compile...any help (dependencies installed!!!)

### ISSUE THREAD

**Issue by michelinok** [JamesP6000/PiCW#1]
g++-4.7 -D_GLIBCXX_DEBUG -std=c++11 -Wall -Werror -fmax-errors=5 -lm PiCW.cpp -pthread -oPiCW
PiCW.cpp: In function 'void send_dit_dah(std::atomic<bool>&, const char&, const double&, std::mt19937&)':
PiCW.cpp:887:3: error: 'sleep_until' is not a member of 'std::this_thread'
PiCW.cpp:893:5: error: 'sleep_until' is not a member of 'std::this_thread'
PiCW.cpp:901:3: error: 'sleep_until' is not a member of 'std::this_thread'
PiCW.cpp:907:5: error: 'sleep_until' is not a member of 'std::this_thread'
PiCW.cpp: In function 'void am_main(std::atomic<bool>&, std::__debug::deque<char>&, std::mutex&, std::condition_variable&, std::__debug::map<char, std::basic_string<char> >&, std::atomic<double>&, std::atomic<bool>&, const bool&, const bool&)':
PiCW.cpp:933:7: error: 'sleep_for' is not a member of 'std::this_thread'
compilation terminated due to -fmax-errors=5.
makefile:6: set di istruzioni per l'obiettivo "PiCW" non riuscito
make: **\* [PiCW] Errore 1

**Comment by JamesP6000** [comment]
Unfortunately, I don't have access to a Pi to debug this right now and I
don't know when I'll be able to. Are you using Raspbian? That's the
distribution I was using when I wrote this code.

James

On Thu, May 14, 2015 at 2:31 AM, michelinok notifications@github.com
wrote:

> g++-4.7 -D_GLIBCXX_DEBUG -std=c++11 -Wall -Werror -fmax-errors=5 -lm
> PiCW.cpp -pthread -oPiCW
> PiCW.cpp: In function 'void send_dit_dah(std::atomic&, const char&, const
> double&, std::mt19937&)':
> PiCW.cpp:887:3: error: 'sleep_until' is not a member of 'std::this_thread'
> PiCW.cpp:893:5: error: 'sleep_until' is not a member of 'std::this_thread'
> PiCW.cpp:901:3: error: 'sleep_until' is not a member of 'std::this_thread'
> PiCW.cpp:907:5: error: 'sleep_until' is not a member of 'std::this_thread'
> PiCW.cpp: In function 'void am_main(std::atomic&, std::__debug::deque&,
> std::mutex&, std::condition_variable&, std::__debug::map >&, std::atomic&,
> std::atomic&, const bool&, const bool&)':
> PiCW.cpp:933:7: error: 'sleep_for' is not a member of 'std::this_thread'
> compilation terminated due to -fmax-errors=5.
> makefile:6: set di istruzioni per l'obiettivo "PiCW" non riuscito
> make: **\* [PiCW] Errore 1
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JamesP6000/PiCW/issues/1.

## 

_Integrity is a binary state - either you have it or you don’t._ - John
Doerr

**Comment by YO3IBZ** [comment]
Hi James,

i have almost the same problem:
pi@yo3ibz ~/PiCW $ make
g++-4.7 -D_GLIBCXX_DEBUG -std=c++11 -Wall -Werror -fmax-errors=5 -lm PiCW.cpp -pthread -oPiCW
make: g++-4.7: Command not found
makefile:6: recipe for target 'PiCW' failed
make: **\* [PiCW] Error 127

can you help me with?

Thank you!
Aurel.

**Comment by JamesP6000** [comment]
Did you all install g++-4.7? Here's the command to install everything
you'll need:

sudo apt-get install git g++-4.7 make grep mawk ntp

Check the BUILD file for detailed information.

James

On Sat, Jun 27, 2015 at 4:39 AM, YO3IBZ notifications@github.com wrote:

> Hi James,
> 
> i have almost the same problem:
> pi@yo3ibz ~/PiCW $ make
> g++-4.7 -D_GLIBCXX_DEBUG -std=c++11 -Wall -Werror -fmax-errors=5 -lm
> PiCW.cpp -pthread -oPiCW
> make: g++-4.7: Command not found
> makefile:6: recipe for target 'PiCW' failed
> make: **\* [PiCW] Error 127
> 
> can you help me with?
> 
> Thank you!
> Aurel.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/JamesP6000/PiCW/issues/1#issuecomment-116017937.

## 

_Integrity is a binary state - either you have it or you don’t._ - John
Doerr

**Comment by pdanilchik** [comment]
I ran into the same problem (on RPi2 with Raspbian Jesse 2015-11-21, apt-get update, upgrade, etc...).  

If you compile using g++-4.9, instead, you ought to see the error go away.  My system seemed to already have that version installed but if yours doesn't you could  'sudo apt-get install g++-4.9'.  To build with this just edit the 'makefile' so that it utilizes version 4.9 instead of 4.7 ('sudo nano makefile' or similar).

If you read the ISSUES file you will note that two users reported indefinite transmit.  In the documentation for 'std::this_thread::sleep_until', I read that there was a bug where it could run indefinitely.  It was subsequently fixed but perhaps the latest 4.7 version of g++ had this removed just so that folks like us would have to investigate and discover this issue. ! ?  I'm not savvy on how software tools such as the gnu compiler are maintained so that is just a wild guess.

Hopefully this fix can get incorporated ?  I don't know how to let the authors know but perhaps they will see this.

Now THE BAD NEWS: I have yet to detect rf on my ham radio with it.  I believe that there are some differences in memory mapping, DMA, and such between the RPi1 and RPi2... so more work needs to be done to make this work on the RPi2, likely.  :-(  -Paul

p.s. It seems that the FM Pi transmitter code may have been patched to work on the RPi2.  I found a reference to some author or contributor of that which led them to the solution: https://www.raspberrypi.org/forums/viewtopic.php?p=699651#p699651

**Comment by AD4GC** [comment]
pi@raspberrypi:~/PiCW $ make
g++-4.7 -D_GLIBCXX_DEBUG -std=c++11 -Wall -Werror -fmax-errors=5 -lm PiCW.cpp -pthread -oPiCW
PiCW.cpp: In function ‘void send_dit_dah(std::atomic<bool>&, const char&, const double&, std::mt19937&)’:
PiCW.cpp:887:3: error: ‘sleep_until’ is not a member of ‘std::this_thread’
PiCW.cpp:893:5: error: ‘sleep_until’ is not a member of ‘std::this_thread’
PiCW.cpp:901:3: error: ‘sleep_until’ is not a member of ‘std::this_thread’
PiCW.cpp:907:5: error: ‘sleep_until’ is not a member of ‘std::this_thread’
PiCW.cpp: In function ‘void am_main(std::atomic<bool>&, std::__debug::deque<char>&, std::mutex&, std::condition_variable&, std::__debug::map<char, std::basic_string<char> >&, std::atomic<double>&, std::atomic<bool>&, const bool&, const bool&)’:
PiCW.cpp:933:7: error: ‘sleep_for’ is not a member of ‘std::this_thread’
compilation terminated due to -fmax-errors=5.
makefile:6: recipe for target 'PiCW' failed
make: **\* [PiCW] Error 1

I see that this is an old conversation, but hopefully still active. I think I am having the same trouble as michelinok and YO3IBZ, I am VERY new to Linux and programming, but it is fun learning. pdanilchik mentioned being able to work around this problem compiling with g++-4.9, how do I compile with it? I do not know where to go to accomplish this? I am using a Rpi B+ with 2016-08-16 Rasbian, I have updated and upgraded the image and kernel, but continue to get the same results. What am I doing wrong? What am I missing?

Thank you,
Greg - AD4GC

**Comment by AD4GC** [comment]
Just in case anyone is watching and had the same problem as I, being a noob, I had installed everything to the home directory "/home/pi". I then installed g++-4.9. To edit "makefile" to change the compiler from g++-4.7 which was causing all my problems to g++-4.9, In the home directory I entered:
    `sudo nano /home/pi/PiCW/makefile`

this opened the nano editor for the "makefile", all I had to do was edit the text for g++-4.7 and replaced it with g++-4.9, save the file and exit the nano editor. I was then able to compile using g++-4.9 exactly as laid out in the Build File. 

This may look and sound trivial and very easy to most, but I am quite proud of myself for being able to figure it out on my own as I have ZERO experience with Linux and programming.

I now have PiCW running, and has been for almost 12 hours testing it, I have not built the LPF yet, but I'm only using a LED with 12" leads, which actually transmits farther than any reasonable expectation on 10 meters, over a mile. I have it set-up as a beacon, I ran a cron job with: 
    `sudo crontab -e` 

edited the job to reflect I wanted it to repeat every minute, it looks something like this:

*/1 \* \* \* \* /usr/local/bin/PiCW --freq 28.29475e6 --self-calibration --wpm 12 T  T  T  T  T  T  T  T  EEEEE  DE AD4GC/B EM77RH
save and exit, and watch it go...
I would prefer it to repeat every 30 seconds, so if anyone has any "How To" please let me know.

As soon as I can get an LPF and Low Power Amplifier built to boost the 10mW to between 2 and 5 watts, I will put it on-air live.

I am having a problem with it wanting to stutter, or not keep time, I'm not sure if it's just the nature of the Pi, but I will keep looking to see what I can find. It will stutter 2 or 3 times out of 10 transmissions.

Thank you James for making this available.
Best wishes (73)
Greg - AD4GC

**Comment by AD4GC** [comment]
OK, after playing around, I have the PiCW running, and for nearly a week or so. I resolved the stuttering problem with the crontab job, I reloaded the SD card with a fresh copy of Raspbian Jessie, no updates nor upgrades, ran the command lines changed g++-4.7 to g++-4.9, created the crontab job and VOILA! 

Now, I am not pleased with crontab scheduling, although, it is pretty cool to be able to run the same message at two different speeds, one following the other. However, I would much like to include the "repeat" function found in the WsprryPi program. I have attempted to copy the "repeat" from WsprryPi to PiCW but have been unsuccessful, someone please help. The Pi I have running will only be used for a CW beacon and nothing else, I would like the message to repeat more often than what crontab will allow.

Thanks,
Greg - AD4GC

**Comment by JamesP6000** [comment]
Hi,

Sorry I'm not able to find time to dig into this deeper. Crontab is
certainly one way to repeatedly run the beacon but you can also use unix
commands. If you want to continuously transmit:

while true ; do PiCW --freq 28.29475e6 --self-calibration --wpm 12 T T T T
T T T T EEEEE DE AD4GC/B EM77RH ; done

If you want to wait 10 seconds between transmissions:

while true ; do PiCW --freq 28.29475e6 --self-calibration --wpm 12 T T T T
T T T T EEEEE DE AD4GC/B EM77RH ; sleep 10 ; done

JP

**Comment by AD4GC** [comment]
Outstanding! Thanks a million for the super fast reply. Thanks for the time and hard work to make this even possible. I will try that as soon as I get back to the computer. Thanks again!
Greg - AD4GC

Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: James Peroulas notifications@github.com Date: 9/8/16  19:20  (GMT-05:00) To: JamesP6000/PiCW PiCW@noreply.github.com Cc: AD4GC ad4gc@yahoo.com, Comment comment@noreply.github.com Subject: Re: [JamesP6000/PiCW] Cannot compile...any help (dependencies installed!!!) (#1) 
Hi,

Sorry I'm not able to find time to dig into this deeper. Crontab is

certainly one way to repeatedly run the beacon but you can also use unix

commands. If you want to continuously transmit:

while true ; do PiCW --freq 28.29475e6 --self-calibration --wpm 12 T T T T

T T T T EEEEE DE AD4GC/B EM77RH ; done

If you want to wait 10 seconds between transmissions:

while true ; do PiCW --freq 28.29475e6 --self-calibration --wpm 12 T T T T

T T T T EEEEE DE AD4GC/B EM77RH ; sleep 10 ; done

JP

**Comment by AD4GC** [comment]
James, that was exactly what I was wanting it to do... another question and I promise I will try to leave you alone, HIHI. How can I get it to automatically start on reboot?

Thanks,
Greg - AD4GC

**Comment by JamesP6000** [comment]
That's a more general UNIX question that I think you can search for on the
internet. I think one solution is to put the command in rc.local and add a
'&' character at the end.

JP

**Comment by lawin1** [comment]
I did everything as pdanilchik and AD4GC suggested, but still cannot compile and this time I'm getting a different error:

g++-4.9 -D_GLIBCXX_DEBUG -std=c++11 -Wall -Werror -fmax-errors=5 -lm PiCW.cpp -pthread -oPiCW
PiCW.cpp: In function ‘void parse_commandline(const int&, char\* const_, double&, double&, double&, bool&, std::string&, bool&, bool&)’:
PiCW.cpp:581:22: error: ‘isnan’ was not declared in this scope
   if (isnan(tone_freq)) {
                      ^
PiCW.cpp:581:22: note: suggested alternative:
In file included from /usr/include/c++/4.9/random:38:0,
                 from PiCW.cpp:28:
/usr/include/c++/4.9/cmath:641:5: note:   ‘std::isnan’
     isnan(_Tp __x)
     ^
makefile:6: recipe for target 'PiCW' failed
make: *_\* [PiCW] Error 1

I am trying to install PiCW on Raspberry Pi 2 with Ubuntu 16.04. WsprryPi installation ran without any issues.

**Comment by lawin1** [comment]
Changed "isnan" to "std::isnan". The line 581 of the file PiCW.cpp. This time compilation ran without errors. 
But PiCW does not transmit at all. The output of any commands shows that it started transmission, but no transmission is actually going on. I compared PiCW with WsprryPi. WsprryPi transmits test tone, but after starting PiCW I can't hear any test tone on SW or MW. Please help. (· · · – – – · · ·)

**Comment by NJ1Q** [comment]
I'm having the same issue.  I made the correction in "makefile."  When it builds, I get a single line of text and then back to prompt.  Using the default test syntax for PiCW, I am unable to hear any transmissions, even though PiCW indicates it's transmitting.  I am using a rPi3 and Jessie.

**Comment by JamesP6000** [comment]
Hi everyone,

I had some time recently and was able to freshen up the code. Using the minimal Jessie image, the code now should compile just fine, as-is.

Furthermore, the code now works on RPi2 and RPi3!

James
